### ISSUE TITLE
Add foxai.__version__ for version verification

### ISSUE THREAD

**Issue by kamilrzechowski** [softwaremill/FoXAI#78]
Allow checking currently installed library version using `print(foxai.__version__`)

**Comment by adamwawrzynski** [comment]
Have you tried to run this command? I've got the correct version printed as a result. I think it's implemented in this file: https://github.com/softwaremill/FoXAI/blob/main/foxai/__init__.py. @kamilrzechowski could you check if this works for you?

**Comment by kamilrzechowski** [comment]
Am I doing something wrong?
![image](https://github.com/softwaremill/FoXAI/assets/49376703/73a4d694-87dc-4c3d-97a4-806faf752c03)

**Comment by adamwawrzynski** [comment]
Couldn't reproduce. Could you try different Python versions and create a new virtual environment for tests?

**Comment by adamwawrzynski** [comment]
Could anyone else reproduce this issue? @rpytel1 @adamjankaczmarek?

**Comment by joannasendorek** [comment]
I also failed to reproduce this error:
```

Type "help", "copyright", "credits" or "license" for more information.
>>> import foxai
>>> foxai.__version__
'0.6.0'
>>> 
```

**Comment by adamwawrzynski** [comment]
Couldn't reproduce it. Reopen this issue by providing additional information which might help us detect the problem.
